PROJECT_IMAGE_BY_SLUG = {
    "esp32-ac-power-monitor": "/assets/images/projects/project-a-01.webp",
    "esp32-ai-object-detector": "/assets/images/projects/project-a-02.webp",
    "esp32-air-quality-monitor": "/assets/images/projects/project-a-03.webp",
    "esp32-ble-beacon": "/assets/images/projects/project-a-04.webp",
    "esp32-cam-face-detection": "/assets/images/projects/project-a-05.webp",
    "esp32-cam-qr-scanner": "/assets/images/projects/project-a-06.webp",
    "esp32-camera-capture-server": "/assets/images/projects/project-a-07.webp",
    "esp32-cnc-controller": "/assets/images/projects/project-a-08.webp",
    "esp32-digital-piano": "/assets/images/projects/project-a-09.webp",
    "esp32-distance-monitoring-system": "/assets/images/projects/project-a-10.webp",
    "esp32-ecg-monitor": "/assets/images/projects/project-a-11.webp",
    "esp32-fire-alarm-system": "/assets/images/projects/project-a-12.webp",
    "esp32-gesture-recognition": "/assets/images/projects/project-a-13.webp",
    "esp32-gps-tracker": "/assets/images/projects/project-a-14.webp",
    "esp32-greenhouse-automation-controller": "/assets/images/projects/project-a-15.webp",
    "esp32-home-climate-automation": "/assets/images/projects/project-a-16.webp",
    "esp32-iot-weather-station": "/assets/images/projects/project-a-17.webp",
    "esp32-ir-remote-control": "/assets/images/projects/project-a-18.webp",
    "esp32-learning-trainer": "/assets/images/projects/project-a-19.webp",
    "esp32-led-matrix-display": "/assets/images/projects/project-a-20.webp",
    "esp32-lightning-detector": "/assets/images/projects/project-b-01.webp",
    "esp32-line-following-robot": "/assets/images/projects/project-b-02.webp",
    "esp32-lora-remote-sensor-node": "/assets/images/projects/project-b-03.webp",
    "esp32-machine-monitoring-node": "/assets/images/projects/project-b-04.webp",
    "esp32-motion-security-alert": "/assets/images/projects/project-b-05.webp",
    "esp32-mqtt-sensor-dashboard": "/assets/images/projects/project-b-06.webp",
    "esp32-neopixel-music-visualizer": "/assets/images/projects/project-b-07.webp",
    "esp32-oled-weather-clock": "/assets/images/projects/project-b-08.webp",
    "esp32-pulse-oximeter-logger": "/assets/images/projects/project-b-09.webp",
    "esp32-rfid-access-control-system": "/assets/images/projects/project-b-10.webp",
    "esp32-rfid-inventory-tracker": "/assets/images/projects/project-b-11.webp",
    "esp32-rgb-led-pattern-controller": "/assets/images/projects/project-b-12.webp",
    "esp32-robot-arm-controller": "/assets/images/projects/project-b-13.webp",
    "esp32-security-camera-system": "/assets/images/projects/project-b-14.webp",
    "esp32-smart-door-lock": "/assets/images/projects/project-b-15.webp",
    "esp32-smart-energy-meter": "/assets/images/projects/project-b-16.webp",
    "esp32-smart-irrigation-system": "/assets/images/projects/project-b-17.webp",
    "esp32-smart-mailbox": "/assets/images/projects/project-b-18.webp",
    "esp32-smart-parking-sensor": "/assets/images/projects/project-b-19.webp",
    "esp32-smart-power-strip": "/assets/images/projects/project-b-20.webp",
}


def project_image_path(slug: str) -> str:
    return PROJECT_IMAGE_BY_SLUG.get(slug, "")
