PROJECT_IMAGE_BY_SLUG = {
    "esp32-ac-power-monitor": "/assets/images/generated/esp32-ac-power-monitor.webp",
    "esp32-ai-object-detector": "/assets/images/generated/esp32-ai-object-detector.webp",
    "esp32-air-quality-monitor": "/assets/images/generated/esp32-air-quality-monitor.webp",
    "esp32-ble-beacon": "/assets/images/generated/esp32-ble-beacon.webp",
    "esp32-cam-face-detection": "/assets/images/generated/esp32-cam-face-detection.webp",
    "esp32-cam-qr-scanner": "/assets/images/generated/esp32-cam-qr-scanner.webp",
    "esp32-camera-capture-server": "/assets/images/generated/esp32-camera-capture-server.webp",
    "esp32-cnc-controller": "/assets/images/generated/esp32-cnc-controller.webp",
    "esp32-digital-piano": "/assets/images/generated/esp32-digital-piano.webp",
    "esp32-distance-monitoring-system": "/assets/images/generated/esp32-distance-monitoring-system.webp",
    "esp32-ecg-monitor": "/assets/images/generated/esp32-ecg-monitor.webp",
    "esp32-fire-alarm-system": "/assets/images/generated/esp32-fire-alarm-system.webp",
    "esp32-gesture-recognition": "/assets/images/generated/esp32-gesture-recognition.webp",
    "esp32-gps-tracker": "/assets/images/generated/esp32-gps-tracker.webp",
    "esp32-greenhouse-automation-controller": "/assets/images/generated/esp32-greenhouse-automation-controller.webp",
    "esp32-home-climate-automation": "/assets/images/generated/esp32-home-climate-automation.webp",
    "esp32-iot-weather-station": "/assets/images/generated/esp32-iot-weather-station.webp",
    "esp32-ir-remote-control": "/assets/images/generated/esp32-ir-remote-control.webp",
    "esp32-learning-trainer": "/assets/images/generated/esp32-learning-trainer.webp",
    "esp32-led-matrix-display": "/assets/images/generated/esp32-led-matrix-display.webp",
    "esp32-lightning-detector": "/assets/images/generated/esp32-lightning-detector.webp",
    "esp32-line-following-robot": "/assets/images/generated/esp32-line-following-robot.webp",
    "esp32-lora-remote-sensor-node": "/assets/images/generated/esp32-lora-remote-sensor-node.webp",
    "esp32-machine-monitoring-node": "/assets/images/generated/esp32-machine-monitoring-node.webp",
    "esp32-motion-security-alert": "/assets/images/generated/esp32-motion-security-alert.webp",
    "esp32-mqtt-sensor-dashboard": "/assets/images/generated/esp32-mqtt-sensor-dashboard.webp",
    "esp32-neopixel-music-visualizer": "/assets/images/generated/esp32-neopixel-music-visualizer.webp",
    "esp32-oled-weather-clock": "/assets/images/generated/esp32-oled-weather-clock.webp",
    "esp32-pulse-oximeter-logger": "/assets/images/generated/esp32-pulse-oximeter-logger.webp",
    "esp32-rfid-access-control-system": "/assets/images/generated/esp32-rfid-access-control-system.webp",
    "esp32-rfid-inventory-tracker": "/assets/images/generated/esp32-rfid-inventory-tracker.webp",
    "esp32-rgb-led-pattern-controller": "/assets/images/generated/esp32-rgb-led-pattern-controller.webp",
    "esp32-robot-arm-controller": "/assets/images/generated/esp32-robot-arm-controller.webp",
    "esp32-security-camera-system": "/assets/images/generated/esp32-security-camera-system.webp",
    "esp32-smart-door-lock": "/assets/images/generated/esp32-smart-door-lock.webp",
    "esp32-smart-energy-meter": "/assets/images/generated/esp32-smart-energy-meter.webp",
    "esp32-smart-irrigation-system": "/assets/images/generated/esp32-smart-irrigation-system.webp",
    "esp32-smart-mailbox": "/assets/images/generated/esp32-smart-mailbox.webp",
    "esp32-smart-parking-sensor": "/assets/images/generated/esp32-smart-parking-sensor.webp",
    "esp32-smart-power-strip": "/assets/images/generated/esp32-smart-power-strip.webp",
    "esp32-smart-street-light": "/assets/images/generated/esp32-smart-street-light.webp",
    "esp32-smart-thermostat": "/assets/images/generated/esp32-smart-thermostat.webp",
    "esp32-soil-moisture-monitor": "/assets/images/generated/esp32-soil-moisture-monitor.webp",
    "esp32-soil-ph-monitor": "/assets/images/generated/esp32-soil-ph-monitor.webp",
    "esp32-uv-index-monitor": "/assets/images/generated/esp32-uv-index-monitor.webp",
    "esp32-vibration-monitor": "/assets/images/generated/esp32-vibration-monitor.webp",
    "esp32-voice-controlled-relay": "/assets/images/generated/esp32-voice-controlled-relay.webp",
    "esp32-water-leak-detector": "/assets/images/generated/esp32-water-leak-detector.webp",
    "esp32-wifi-robot-controller": "/assets/images/generated/esp32-wifi-robot-controller.webp",
}


def project_image_path(slug: str) -> str:
    return PROJECT_IMAGE_BY_SLUG.get(slug, "")
